### PR TITLE
Compile socket without stdio backend

### PR DESCRIPTION
**Pull request by tyt2y3**
https://github.com/SeaQL/sea-streamer/issues/34

```sh
cargo build --no-default-features --features=backend-file
```

### CODE REVIEW

**Comment by tyt2y3** [comment]
@holmofy would appreciate if you can try this

**Comment by holmofy** [comment]
Thanks for fixing this issue, I can continue with the spring-rs task.

**Comment by tyt2y3** [comment]
Cheers, please let me know if you find any problems.

**Comment by holmofy** [comment]
OK. This library solved a big problem of mine. Thank you for providing this library, which unifies the abstraction of backend stream processing.

**Comment by holmofy** [comment]
Please tell me when the new version of crate will be released

**Pull request merged**
