### PR TITLE
feat: from url and from iterator for streameruri

### LINKED ISSUE #26: impl From<Url> for StreamerUri
## Motivation

Currently we cannot convert a `Url` into a `StreamerUri` unless we transform it back to a `String`.

## Proposed Solutions

```rs
impl From<Url> for StreamerUri {
    fn from(value: Url) -> Self {
        Self { nodes: vec![value] }
    }
}
```

## Additional Information

Maybe in the future accept a generic that `impl IntoStreamerUri`. Something like _sea-orm_.

### PR DESCRIPTION
**Pull request by carlocorradini**
## PR Info

Added `From<Url>` and `FromIterator<Url>` for `StreamerUri`.

- Closes
   - Fix #26 

## New Features

- [x] `impl From<Url> for StreamerUri`
   ```rs
   let url: Url = "proto://sea-ql.org:1234".parse().unwrap();
   let uri: StreamerUri = url.into();
   ```
- [x] `impl FromIterator<Url> for StreamerUri`
   ```rs
   let urls: [Url; 3] = ["proto://sea-ql.org:1".parse().unwrap() ,"proto://sea-ql.org:2".parse().unwrap(), "proto://sea-ql.org:3".parse().unwrap()];
   let uri: StreamerUri = StreamerUri::from_iter(urls.into_iter());
   ```

### CODE REVIEW

**Comment by carlocorradini** [comment]
Unfortunately the following does not compile due to `Send` (it is required?)

```rs
fn connect(
        streamer: impl Into<StreamerUri>,
        options: Self::ConnectOptions,
) -> impl Future<Output = StreamResult<Self, Self::Error>> + Send;
```

**Comment by chris-numeus** [comment]
it is possible, if we add `Send` as a trait bound?

```rust
fn connect<S>(
        streamer: S,
        options: Self::ConnectOptions,
) -> impl Future<Output = StreamResult<Self, Self::Error>> + Send
where S: Into<StreamerUri> + Send, {}
```

**Comment by tyt2y3** [comment]
it is possible, if we add `Send` as a trait bound?

```rust
fn connect<S>(
        streamer: S,
        options: Self::ConnectOptions,
) -> impl Future<Output = StreamResult<Self, Self::Error>> + Send
where S: Into<StreamerUri> + Send, {}
```

**Comment by carlocorradini** [comment]
Done 🥳

**Comment by tyt2y3** [comment]
Sad, there was a bunch of errors, where type inference fails.

**Comment by carlocorradini** [comment]
I'll fix it ASAP.
Sadness... I've run `cargo build --all --all-features` (same for test) and it worked.

**Comment by tyt2y3** [comment]
It can be reproduced in `cargo test --no-run`. May be we change to `parse::< StreamerUri >()` in all cases

**Comment by carlocorradini** [comment]
Done 🥳

**Review by tyt2y3 — APPROVED** [review]
Thank you

**Pull request merged**
